import cv2
import numpy as np
from matplotlib import pyplot as plt

x = plt.imread("logo8.png")
x_hsv = cv2.cvtColor(x,cv2.COLOR_RGB2HSV)
x_hls = cv2.cvtColor(x,cv2.COLOR_RGB2HLS)
x_ycrcb = cv2.cvtColor(x,cv2.COLOR_RGB2YCR_CB)
plt.subplot(4, 4, 1).imshow(x, cmap="gray", aspect=None, interpolation=None, alpha=None)  
plt.title("RGB")
plt.subplot(4, 4, 2).imshow(x[:,:,0], cmap="gray", aspect=None, interpolation=None, alpha=None)  
plt.title("R")
plt.subplot(4, 4, 3).imshow(x[:,:,1], cmap="gray", aspect=None, interpolation=None, alpha=None)  
plt.title("G")
plt.subplot(4, 4, 4).imshow(x[:,:,2], cmap="gray", aspect=None, interpolation=None, alpha=None)  
plt.title("B")
plt.subplot(4, 4, 5).imshow(x_hsv, cmap="gray", aspect=None, interpolation=None, alpha=None)  
plt.title("HSV")
plt.subplot(4, 4, 6).imshow(x_hsv[:,:,0], cmap="gray", aspect=None, interpolation=None, alpha=None)  
plt.title("H")
plt.subplot(4, 4, 7).imshow(x_hsv[:,:,1], cmap="gray", aspect=None, interpolation=None, alpha=None)  
plt.title("S")
plt.subplot(4, 4, 8).imshow(x_hsv[:,:,2], cmap="gray", aspect=None, interpolation=None, alpha=None)  
plt.title("V")
plt.subplot(4, 4, 9).imshow(x_hls, cmap="gray", aspect=None, interpolation=None, alpha=None)  
plt.title("HSL")
plt.subplot(4, 4, 10).imshow(x_hls[:,:,0], cmap="gray", aspect=None, interpolation=None, alpha=None)  
plt.title("H")
plt.subplot(4, 4, 11).imshow(x_hls[:,:,1], cmap="gray", aspect=None, interpolation=None, alpha=None)  
plt.title("S")
plt.subplot(4, 4, 12).imshow(x_hls[:,:,2], cmap="gray", aspect=None, interpolation=None, alpha=None)  
plt.title("L")
plt.subplot(4, 4, 13).imshow(x_ycrcb, cmap="gray", aspect=None, interpolation=None, alpha=None)  
plt.title("YCrCb")
plt.subplot(4, 4, 14).imshow(x_ycrcb[:,:,0], cmap="gray", aspect=None, interpolation=None, alpha=None)  
plt.title("Y")
plt.subplot(4, 4, 15).imshow(x_ycrcb[:,:,1], cmap="gray", aspect=None, interpolation=None, alpha=None)  
plt.title("Cr")
plt.subplot(4, 4, 16).imshow(x_ycrcb[:,:,2], cmap="gray", aspect=None, interpolation=None, alpha=None)  
plt.title("Cb")
plt.show()